name = "phony"
version = "1.3.0"

links = [{ title = "Gleam", href = "https://gleam.run" }]
description = "An international phone number validator"
gleam = ">= 1.4.0"
licences = ["Apache-2.0"]
repository = { type = "github", user = "massivefermion", repo = "phony" }
internal_modules = ["phony/metadata"]


[dependencies]
gleam_stdlib = ">= 0.49.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.3"
